name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zlib1g-dev
        pip install --upgrade pip setuptools wheel cython buildozer
        pip install kivy
    - name: Build APK
      run: |
        yes | buildozer android debug
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: mirror-apk
        path: bin/*.apk
